title: Riley Shahar
email: rshahar@sas.upenn.edu
description: math educator, homotopy theorist, graduate student at Penn
baseurl: ""
url: https://rileyshahar.com # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/rileyshahar/website

# build
markdown: kramdown
kramdown:
  math_engine: katex
