title: Riley Shahar
email: rshahar@sas.upenn.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: https://rileyshahar.com # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/rileyshahar/website

# build
markdown: kramdown
kramdown:
  math_engine: katex
