#!/usr/bin/env python3
"""Generate an academic CV (LaTeX + PDF) from _data/*.yaml.

Reads:
    _data/cv.yaml                header info
    _data/education.yaml         degrees and training
    _data/awards.yaml            fellowships, grants, honors
    _data/research-experience.yaml   summer research positions
    _data/papers.yaml            research papers and preprints
    _data/expository-writing.yaml    notes, articles
    _data/research-talks.yaml    research talks
    _data/expository-talks.yaml  expository talks
    _data/teaching.yaml          courses taught/assisted
    _data/service.yaml           organizing, mentoring

Writes:
    assets/cv.tex                generated LaTeX source
    assets/cv.pdf                compiled PDF (with --compile)

Requires `tectonic` on PATH for --compile.
"""
from __future__ import annotations

import argparse
import datetime
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "_data"


# ---------------------------------------------------------------- utilities

_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(s: Any) -> str:
    if s is None:
        return ""
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in str(s))


def preserve_math_escape(s: Any) -> str:
    """Escape LaTeX specials outside ``$$…$$`` math; leave math unchanged."""
    if s is None:
        return ""
    parts = re.split(r"(\$\$[^$]*\$\$)", str(s))
    return "".join(p if p.startswith("$$") else tex_escape(p) for p in parts)


def initialize(name: str) -> str:
    """'Kyle Ormsby' -> 'K. Ormsby'. Leaves already-initialized names alone."""
    name = name.strip()
    if re.match(r"^[A-Z]\.\s", name):
        return name
    parts = name.split()
    if len(parts) < 2:
        return name
    return f"{parts[0][0]}. {' '.join(parts[1:])}"


def coauthor_name(c: Any) -> str:
    if isinstance(c, dict):
        return str(c.get("name", ""))
    return str(c)


def date_key(d: Any):
    """Sort key that works for yaml-parsed ``datetime.date`` or strings."""
    if isinstance(d, datetime.date):
        return d.isoformat()
    return str(d) if d else ""


def year_of(d: Any) -> str:
    if isinstance(d, datetime.date):
        return str(d.year)
    return str(d)[:4] if d else ""


_MONTHS = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def month_year(d: Any) -> str:
    if isinstance(d, datetime.date):
        return f"{_MONTHS[d.month]} {d.year}"
    try:
        parsed = datetime.date.fromisoformat(str(d))
    except (TypeError, ValueError):
        return str(d) if d else ""
    return f"{_MONTHS[parsed.month]} {parsed.year}"


def load(name: str):
    path = DATA / f"{name}.yaml"
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text()) or []


# ----------------------------------------------------------------- template

PREAMBLE = r"""%% Auto-generated by scripts/build_cv.py. Do not edit by hand.
\documentclass[11pt,letterpaper]{article}

\usepackage[margin=1in]{geometry}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage[hidelinks]{hyperref}

\pagenumbering{gobble}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}

% Small-caps section headings with a thin rule underneath.
\titleformat{\section}
  {\normalsize\scshape}
  {}{0pt}{}
  [\vspace{-0.4ex}{\color{black!40}\titlerule[0.4pt]}]
\titlespacing*{\section}{0pt}{1.3\baselineskip}{0.4\baselineskip}

% A non-bulleted list for institutional entries (education, research
% experience) so we can align content left and dates right.
\newenvironment{cventries}
  {\begin{list}{}{%
      \setlength{\leftmargin}{1em}%
      \setlength{\itemindent}{0pt}%
      \setlength{\listparindent}{0pt}%
      \setlength{\itemsep}{0.8ex}%
      \setlength{\parsep}{0pt}%
      \setlength{\topsep}{0.3ex}%
    }}
  {\end{list}}

\begin{document}
"""


# ----------------------------------------------------------------- sections

def header(cv: dict) -> str:
    name = tex_escape(f"{cv['first']} {cv['last']}")
    right: list[str] = []
    if cv.get("pronouns"):
        right.append(f"Pronouns: {tex_escape(cv['pronouns'])}")
    if cv.get("email"):
        email = cv["email"]
        right.append(
            rf"Email: \href{{mailto:{email}}}{{{tex_escape(email)}}}"
        )
    if cv.get("website"):
        display = tex_escape(cv.get("website_display") or cv["website"])
        right.append(rf"Web: \href{{{cv['website']}}}{{{display}}}")
    if cv.get("office"):
        right.append(f"Office: {tex_escape(cv['office'])}")

    right_block = " \\\\\n  ".join(right)

    return rf"""
\noindent
\begin{{minipage}}[t]{{0.55\textwidth}}
  \vspace{{0pt}}{{\LARGE\scshape {name}}}
\end{{minipage}}\hfill
\begin{{minipage}}[t]{{0.45\textwidth}}
  \vspace{{0pt}}\raggedleft\small
  {right_block}
\end{{minipage}}
\vspace{{0.5ex}}

"""


def section(title: str, body: str) -> str:
    body = body.strip()
    if not body:
        return ""
    return f"\n\\section*{{{title}}}\n{body}\n"


def interests(cv: dict) -> str:
    ri = cv.get("research_interests")
    if not ri:
        return ""
    return section("Research interests", tex_escape(str(ri).strip()))


def education_section(entries: list[dict]) -> str:
    parts = [r"\begin{cventries}"]
    for e in entries:
        inst = tex_escape(e["institution"])
        loc = tex_escape(e.get("location", ""))
        degree = tex_escape(e["degree"])
        start = str(e.get("start", ""))
        end = str(e.get("end", ""))
        if end and e.get("expected"):
            end = f"{end} (expected)"
        dates = f"{start}--{end}" if (start and end) else (start or end)

        body = [rf"\item \textbf{{{inst}}} \hfill {loc}\\"]
        body.append(f"{degree} \\hfill {dates}")
        if e.get("thesis"):
            thesis = preserve_math_escape(e["thesis"])
            body.append(rf"\\[0.2ex] {{\small Thesis: ``\textit{{{thesis}}}''}}")
        advisors = e.get("advisors") or (
            [e["advisor"]] if e.get("advisor") else []
        )
        if advisors:
            adv = ", ".join(tex_escape(a) for a in advisors)
            label = "Advisor" if len(advisors) == 1 else "Advisors"
            body.append(rf"\\[0.2ex] {{\small {label}: {adv}}}")
        parts.append("\n".join(body))
    parts.append(r"\end{cventries}")
    return "\n".join(parts)


def _join_coauthors(coauthors: list) -> str:
    names = [initialize(coauthor_name(c)) for c in coauthors]
    names = [tex_escape(n) for n in names if n]
    if not names:
        return ""
    if len(names) == 1:
        return f"Joint with {names[0]}."
    if len(names) == 2:
        return f"Joint with {names[0]} and {names[1]}."
    return f"Joint with {', '.join(names[:-1])}, and {names[-1]}."


def papers_section(entries: list[dict]) -> str:
    parts = [
        r"\begin{itemize}[leftmargin=1.2em,itemsep=0.6ex,topsep=0.2ex]"
    ]
    sorted_entries = sorted(
        entries, key=lambda p: date_key(p.get("date")), reverse=True
    )
    for p in sorted_entries:
        title = preserve_math_escape(p["title"])
        year = year_of(p.get("date"))
        chunks = [rf"\textit{{{title}}}."]
        if p.get("coauthors"):
            chunks.append(_join_coauthors(p["coauthors"]))
        if year:
            chunks.append(f"{year}.")
        if p.get("arxiv"):
            chunks.append(
                rf"Available at \href{{https://arxiv.org/abs/{p['arxiv']}}}"
                rf"{{arXiv:{p['arxiv']}}}."
            )
        if p.get("status"):
            chunks.append(rf"\textit{{{tex_escape(str(p['status']).capitalize())}.}}")
        parts.append(r"\item " + " ".join(chunks))
    parts.append(r"\end{itemize}")
    return "\n".join(parts)


def expository_writing_section(entries: list[dict]) -> str:
    parts = [
        r"\begin{itemize}[leftmargin=1.2em,itemsep=0.5ex,topsep=0.2ex]"
    ]
    sorted_entries = sorted(
        entries, key=lambda p: str(p.get("year", "")), reverse=True
    )
    for p in sorted_entries:
        title = preserve_math_escape(p["title"])
        year = str(p.get("year", ""))
        chunks = [rf"\textit{{{title}}}."]
        if year:
            chunks.append(f"{year}.")
        parts.append(r"\item " + " ".join(chunks))
    parts.append(r"\end{itemize}")
    return "\n".join(parts)


def awards_section(entries: list[dict]) -> str:
    parts = [
        r"\begin{itemize}[leftmargin=1.2em,itemsep=0.5ex,topsep=0.2ex]"
    ]
    for a in entries:
        name = tex_escape(a["name"])
        issuer = tex_escape(a.get("issuer", ""))
        date = tex_escape(a.get("date", ""))
        line = rf"\item {name} \hfill {date}"
        if issuer:
            line += rf"\\ {{\small\textit{{{issuer}}}}}"
        if a.get("note"):
            line += rf"\\ {{\small {tex_escape(str(a['note']).strip())}}}"
        parts.append(line)
    parts.append(r"\end{itemize}")
    return "\n".join(parts)


def experience_section(entries: list[dict]) -> str:
    parts = [r"\begin{cventries}"]
    for e in entries:
        inst = tex_escape(e["institution"])
        loc = tex_escape(e.get("location", ""))
        title = tex_escape(e["title"])
        date = tex_escape(e.get("date", ""))
        body = [rf"\item \textbf{{{inst}}} \hfill {loc}\\"]
        body.append(f"{title} \\hfill {date}")
        if e.get("advisors"):
            adv = ", ".join(tex_escape(a) for a in e["advisors"])
            label = "Advisor" if len(e["advisors"]) == 1 else "Advisors"
            body.append(rf"\\[0.2ex] {{\small {label}: {adv}}}")
        if e.get("description"):
            desc = preserve_math_escape(str(e["description"]).strip())
            body.append(rf"\\[0.2ex] {{\small {desc}}}")
        parts.append("\n".join(body))
    parts.append(r"\end{cventries}")
    return "\n".join(parts)


def talks_section(research: list[dict], expository: list[dict]) -> str:
    combined = []
    for t in research:
        combined.append({**t, "_kind": "research"})
    for t in expository:
        combined.append({**t, "_kind": "expository"})
    combined.sort(key=lambda t: date_key(t.get("date")), reverse=True)

    parts = [
        r"\begin{itemize}[leftmargin=1.2em,itemsep=0.3ex,topsep=0.2ex]"
    ]
    for t in combined:
        title = preserve_math_escape(t["title"])
        venue = tex_escape(t.get("venue", ""))
        if t.get("venue_url"):
            venue = rf"\href{{{t['venue_url']}}}{{{venue}}}"
        date = tex_escape(month_year(t.get("date")))
        line = rf"\item \textit{{{title}}}"
        if venue:
            line += f", {venue}"
        line += rf" \hfill {date}"
        parts.append(line)
    parts.append(r"\end{itemize}")
    return "\n".join(parts)


_TERM_ORDER = {"Spring": 0, "Summer": 1, "Fall": 2}


def _teaching_sort(e: dict):
    year = -int(e.get("year", 0))
    term = _TERM_ORDER.get(e.get("term"), 5)
    week = int(e.get("week") or 0)
    return (year, -term, week)


def teaching_section(entries: list[dict]) -> str:
    groups: dict[str, list[dict]] = {}
    for e in entries:
        groups.setdefault(e.get("inst", "(other)"), []).append(e)

    preferred = [
        "University of Pennsylvania",
        "SCI Chester",
        "Mathcamp",
        "Reed College",
    ]
    ordered = [k for k in preferred if k in groups] + \
              [k for k in groups if k not in preferred]

    display_name = {
        "SCI Chester": "State Correctional Institution Chester",
        "Mathcamp": "Canada/USA Mathcamp",
    }

    parts = []
    for inst in ordered:
        label = display_name.get(inst, inst)
        parts.append(rf"\textbf{{{tex_escape(label)}}}")
        parts.append(
            r"\begin{itemize}[leftmargin=1.2em,itemsep=0.2ex,topsep=0.3ex]"
        )
        for e in sorted(groups[inst], key=_teaching_sort):
            title = tex_escape(e["title"])
            code = tex_escape(e.get("code", ""))
            term = e.get("term")
            year = e.get("year")
            week = e.get("week")
            if term and year:
                when = f"{term} {year}"
            elif week and year:
                when = f"{year}, Week {week}"
            elif year:
                when = str(year)
            else:
                when = ""
            left = rf"\textit{{{title}}}"
            if code:
                left = rf"{code}: {left}"
            if e.get("coteachers"):
                co = ", ".join(
                    tex_escape(coauthor_name(c)) for c in e["coteachers"]
                )
                left += f", with {co}"
            parts.append(rf"\item {left} \hfill {tex_escape(when)}")
        parts.append(r"\end{itemize}")
    return "\n".join(parts)


def service_section(entries: list[dict]) -> str:
    parts = [
        r"\begin{itemize}[leftmargin=1.2em,itemsep=0.4ex,topsep=0.2ex]"
    ]
    for s in entries:
        role = tex_escape(s["role"])
        venue = tex_escape(s["venue"])
        if s.get("url"):
            venue = rf"\href{{{s['url']}}}{{{venue}}}"
        date = tex_escape(s.get("date", ""))
        line = rf"\item \textbf{{{role}}}, {venue}"
        if s.get("coorganizers"):
            co = ", ".join(
                tex_escape(coauthor_name(c)) for c in s["coorganizers"]
            )
            line += f", with {co}"
        line += rf" \hfill {date}"
        parts.append(line)
    parts.append(r"\end{itemize}")
    return "\n".join(parts)


# -------------------------------------------------------------------- build

def render() -> str:
    cv = load("cv")
    if not isinstance(cv, dict):
        raise RuntimeError("_data/cv.yaml must be a mapping")

    pieces = [PREAMBLE, header(cv), interests(cv)]

    if (edu := load("education")):
        pieces.append(section("Education", education_section(edu)))
    if (papers := load("papers")):
        pieces.append(section("Papers and preprints", papers_section(papers)))
    if (expo := load("expository-writing")):
        pieces.append(section("Expository writing", expository_writing_section(expo)))
    if (awards := load("awards")):
        pieces.append(section("Fellowships and awards", awards_section(awards)))
    if (exp := load("research-experience")):
        pieces.append(section("Research experience", experience_section(exp)))
    if (teaching := load("teaching")):
        pieces.append(section("Teaching", teaching_section(teaching)))

    research_talks = load("research-talks")
    expository_talks = load("expository-talks")
    if research_talks or expository_talks:
        pieces.append(
            section("Talks", talks_section(research_talks, expository_talks))
        )

    if (service := load("service")):
        pieces.append(section("Service and organization", service_section(service)))

    pieces.append("\n\\end{document}\n")
    return "".join(pieces)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=ROOT / "assets" / "cv.tex",
                    help="Path to write the .tex file (default: assets/cv.tex)")
    ap.add_argument("--compile", action="store_true",
                    help="After writing .tex, compile to PDF with tectonic")
    args = ap.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render())
    print(f"wrote {args.out.relative_to(ROOT)}")

    if args.compile:
        tectonic = shutil.which("tectonic")
        if not tectonic:
            sys.exit("error: tectonic not found on PATH")
        subprocess.run(
            [tectonic, args.out.name],
            cwd=args.out.parent,
            check=True,
        )
        print(f"wrote {args.out.with_suffix('.pdf').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
