#!/usr/bin/env python3
"""Generate a Typst CV using the pro-academic-cv template."""

from __future__ import annotations

import argparse
import datetime
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "_data"


# ---------------------------------------------------------------- utilities

_TYPST_ESCAPES = {
    "\\": "\\\\",
    "#": "\\#",
    "$": "\\$",
    "@": "\\@",
    "*": "\\*",
    "_": "\\_",
    "`": "\\`",
    "<": "\\<",
    ">": "\\>",
    "[": "\\[",
    "]": "\\]",
}


def ty(s: Any) -> str:
    """Escape a string for use inside a Typst content block ``[...]``."""
    if s is None:
        return ""
    return "".join(_TYPST_ESCAPES.get(ch, ch) for ch in str(s))


def code_str(s: Any) -> str:
    """Escape a string for use inside a Typst double-quoted code-mode string."""
    if s is None:
        return ""
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


_MD_INLINE_RE = re.compile(
    r"(\[[^\]]+\]\([^)]+\)|\$\$[^$]+\$\$|\$[^$\n]+\$|`[^`\n]+`|\*\*[^*\n]+\*\*|__[^_\n]+__|(?<!\*)\*[^*\n]+\*(?!\*)|(?<!_)_[^_\n]+_(?!_))"
)
_MD_LINK_RE = re.compile(r"^\[([^\]]+)\]\(([^)]+)\)$")


def md(s: Any) -> str:
    """Convert inline Markdown from YAML data into Typst content markup."""
    if s is None:
        return ""
    out = []
    for part in re.split(_MD_INLINE_RE, str(s)):
        if not part:
            continue
        if match := _MD_LINK_RE.match(part):
            label, url = match.groups()
            out.append(f'#link("{code_str(url)}")[{md(label)}]')
        elif (part.startswith("$$") and part.endswith("$$")) or (
            part.startswith("$") and part.endswith("$")
        ):
            out.append(f"${part.strip('$')}$")
        elif part.startswith("`") and part.endswith("`"):
            out.append(part)
        elif (part.startswith("**") and part.endswith("**")) or (
            part.startswith("__") and part.endswith("__")
        ):
            out.append(f"*{md(part[2:-2])}*")
        elif (part.startswith("*") and part.endswith("*")) or (
            part.startswith("_") and part.endswith("_")
        ):
            out.append(f"_{md(part[1:-1])}_")
        else:
            out.append(ty(part))
    return "".join(out)


def initialize(name: str) -> str:
    """'Kyle Ormsby' -> 'K. Ormsby'. Leaves already-initialized names alone."""
    name = name.strip()
    if re.match(r"^[A-Z]\.\s", name):
        return name
    parts = name.split()
    if len(parts) < 2:
        return name
    return f"{parts[0][0]}. {' '.join(parts[1:])}"


def coauthor_name(c: Any) -> str:
    if isinstance(c, dict):
        return str(c.get("name", ""))
    return str(c)


def date_key(d: Any):
    if isinstance(d, datetime.date):
        return d.isoformat()
    return str(d) if d else ""


def year_of(d: Any) -> str:
    if isinstance(d, datetime.date):
        return str(d.year)
    return str(d)[:4] if d else ""


_MONTHS = [
    "",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]


def month_year(d: Any) -> str:
    if isinstance(d, datetime.date):
        return f"{_MONTHS[d.month]} {d.year}"
    try:
        parsed = datetime.date.fromisoformat(str(d))
    except (TypeError, ValueError):
        return str(d) if d else ""
    return f"{_MONTHS[parsed.month]} {parsed.year}"


def long_date(d: datetime.date) -> str:
    return f"{_MONTHS[d.month]} {d.day}, {d.year}"


def load(name: str):
    path = DATA / f"{name}.yaml"
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text()) or []


# ----------------------------------------------------------------- template

PREAMBLE = """// Auto-generated by scripts/build_cv.py. Do not edit by hand.
#import "@preview/pro-academic-cv:0.1.0": *

#let cv-date(body) = box[#text(size: 0.9em, style: "normal")[#body]]

#let cv-row2col(left, rhs) = grid(
  columns: (1fr, auto),
  column-gutter: 0.5em,
  [#left],
  [#cv-date(rhs)],
)

"""

DATE_TEXT_ARGS = '(size: 0.9em, style: "normal")'


# --------------------------------------------------------- rendering helpers


def _r2c2_entry(
    *,
    top_left: str = "",
    top_right: str = "",
    bottom_left: str = "",
    bottom_right: str = "",
    top_right_args: str | None = None,
    list_items: list[str] | None = None,
) -> str:
    """Emit a single entry dict for ``r2c2-entry-list``."""
    lines = [
        "  (",
        "    entry-header-args: (",
        f"      top-left: [{top_left}],",
        f"      top-right: [{top_right}],",
        f"      bottom-left: [{bottom_left}],",
        f"      bottom-right: [{bottom_right}],",
    ]
    if top_right_args:
        lines.append(f"      top-right-args: {top_right_args},")
    lines.append("    ),")
    if list_items:
        lines.append("    list-items: (")
        for item in list_items:
            lines.append(f"      [{item}],")
        lines.append("    ),")
    lines.append("  )")
    return "\n".join(lines)


def _r2c2_list(title: str, entries: list[str]) -> str:
    body = ",\n".join(entries)
    return f"== {title}\n\n#r2c2-entry-list(\n{body},\n)\n\n"


def _row_list(title: str, rows: list[tuple[str, str]]) -> str:
    """Emit ``multi-line-list(row2col(...), ...)`` for a flat bulleted list."""
    lines = [f"  cv-row2col([{left}], [{right}])" for left, right in rows]
    body = ",\n".join(lines)
    return f"== {title}\n\n#multi-line-list(\n{body},\n)\n\n"


def _join_coauthors(coauthors: list) -> str:
    names = [initialize(coauthor_name(c)) for c in coauthors]
    names = [md(n) for n in names if n]
    if not names:
        return ""
    if len(names) == 1:
        return f"Joint with {names[0]}."
    if len(names) == 2:
        return f"Joint with {names[0]} and {names[1]}."
    return f"Joint with {', '.join(names[:-1])}, and {names[-1]}."


# ----------------------------------------------------------------- sections


def header(cv: dict) -> str:
    name = f"{cv.get('first', '')} {cv.get('last', '')}".strip()

    primary: list[str] = []
    if cv.get("email"):
        email = cv["email"]
        primary.append(f'#link("mailto:{code_str(email)}")[{ty(email)}]')
    if cv.get("website"):
        display = md(cv.get("website_display") or cv["website"])
        primary.append(f'#link("{code_str(cv["website"])}")[{display}]')

    secondary: list[str] = []
    if cv.get("pronouns"):
        secondary.append(f"Pronouns: {md(cv['pronouns'])}")
    if cv.get("office"):
        secondary.append(f"Office: {md(cv['office'])}")

    tertiary_parts: list[str] = []
    if cv.get("department"):
        tertiary_parts.append(md(cv["department"]))
    if cv.get("affiliation"):
        tertiary_parts.append(md(cv["affiliation"]))
    tertiary = ", ".join(tertiary_parts)

    return (
        "#show: resume.with(\n"
        "  author-info: (\n"
        f'    name: "{code_str(name)}",\n'
        f"    primary-info: [{' | '.join(primary)}],\n"
        f"    secondary-info: [{' | '.join(secondary)}],\n"
        f"    tertiary-info: [{tertiary}],\n"
        "  ),\n"
        ")\n\n"
    )


def interests_section(cv: dict) -> str:
    ri = cv.get("research_interests")
    if not ri:
        return ""
    return f"== Research interests\n\n{md(str(ri).strip())}\n\n"


# def updated_section() -> str:
#     today = long_date(datetime.date.today())
#     return (
#         '#align(right)[#text(size: 0.8em, style: "italic")'
#         f"[Last updated: {ty(today)}]]\n\n"
#     )


def education_section(entries: list[dict]) -> str:
    blocks: list[str] = []
    for e in entries:
        inst = md(e["institution"])
        loc = md(e.get("location", ""))
        degree = md(e["degree"])
        start = str(e.get("start", ""))
        end = str(e.get("end", ""))
        if end and e.get("expected"):
            end = f"{end} (expected)"
        dates = f"{start}--{end}" if (start and end) else (start or end)

        items: list[str] = []
        for honor in e.get("honors") or []:
            items.append(f"_{md(honor)}_")
        advisors = e.get("advisors") or ([e["advisor"]] if e.get("advisor") else [])
        if advisors:
            names = ", ".join(md(a) for a in advisors)
            label = "Advisor" if len(advisors) == 1 else "Advisors"
            items.append(f"{label}: {names}")
        if notes := e.get("notes"):
            for note in notes:
                items.append(md(note))

        blocks.append(
            _r2c2_entry(
                top_left=inst,
                top_right=dates,
                bottom_left=degree,
                bottom_right=loc,
                top_right_args=DATE_TEXT_ARGS,
                list_items=items,
            )
        )
    return _r2c2_list("Education", blocks)


def papers_section(entries: list[dict]) -> str:
    sorted_entries = sorted(
        entries, key=lambda p: date_key(p.get("date")), reverse=True
    )
    items: list[str] = []
    for p in sorted_entries:
        title = md(p["title"])
        year = year_of(p.get("date"))
        chunks = [f"_{title}_."]
        if p.get("coauthors"):
            chunks.append(_join_coauthors(p["coauthors"]))
        if year:
            chunks.append(f"{year}.")
        if p.get("arxiv"):
            arxiv = p["arxiv"]
            chunks.append(
                f'Available at #link("https://arxiv.org/abs/{code_str(arxiv)}")'
                f"[arXiv:{ty(arxiv)}]."
            )
        status = p.get("status")
        if status:
            chunks.append(f"_{md(str(status).capitalize())}._")
        value = " ".join(chunks)
        items.append(f"- {value}")
    body = "\n".join(items)
    return f"== Papers and preprints\n\n{body}\n\n"


def awards_section(entries: list[dict]) -> str:
    blocks: list[str] = []
    for a in entries:
        name = md(a["name"])
        issuer = md(a.get("issuer", ""))
        date = md(a.get("date", ""))
        items: list[str] = []
        if a.get("note"):
            items.append(md(str(a["note"]).strip()))
        blocks.append(
            _r2c2_entry(
                top_left=name,
                top_right=date,
                bottom_left=issuer,
                bottom_right="",
                top_right_args=DATE_TEXT_ARGS,
                list_items=items,
            )
        )
    return _r2c2_list("Fellowships and awards", blocks)


def experience_section(entries: list[dict]) -> str:
    blocks: list[str] = []
    for e in entries:
        title = md(e["title"])
        loc = md(e.get("location", ""))
        inst = md(e["institution"])
        date = md(e.get("date", ""))
        items: list[str] = []
        if e.get("advisors"):
            adv = ", ".join(md(a) for a in e["advisors"])
            label = "Advisor" if len(e["advisors"]) == 1 else "Advisors"
            items.append(f"{label}: {adv}")
        if e.get("description"):
            items.append(md(str(e["description"]).strip()))
        blocks.append(
            _r2c2_entry(
                top_left=title,
                top_right=date,
                bottom_left=inst,
                bottom_right=loc,
                top_right_args=DATE_TEXT_ARGS,
                list_items=items,
            )
        )
    return _r2c2_list("Research experience", blocks)


_TERM_ORDER = {"Spring": 0, "Summer": 1, "Fall": 2}
_SEMESTER_IDX = {"Spring": 0, "Summer": 1, "Fall": 2}
_SEMESTERS_PER_YEAR = 3
# Spring -> Fall has a gap of 2 (Summer between); collapse into a single range.
_MAX_CONSECUTIVE_GAP = 2


def _semester_index(year: int, term: str) -> int:
    return year * _SEMESTERS_PER_YEAR + _SEMESTER_IDX[term]


def _teaching_sort(e: dict):
    year = -int(e.get("year", 0))
    term = _TERM_ORDER.get(e.get("term"), 5)
    week = int(e.get("week") or 0)
    return (year, -term, week)


def _format_term_ranges(term_years: list[tuple[int, str]]) -> str:
    if not term_years:
        return ""
    indexed = sorted({(_semester_index(y, t), t, y) for (y, t) in term_years})
    runs: list[tuple[tuple[int, str, int], tuple[int, str, int]]] = []
    start = prev = indexed[0]
    for cur in indexed[1:]:
        if cur[0] - prev[0] <= _MAX_CONSECUTIVE_GAP:
            prev = cur
        else:
            runs.append((start, prev))
            start = prev = cur
    runs.append((start, prev))

    def fmt(run):
        (_, t_s, y_s), (_, t_e, y_e) = run
        if (t_s, y_s) == (t_e, y_e):
            return f"{t_s} {y_s}"
        return f"{t_s} {y_s}--{t_e} {y_e}"

    return ", ".join(fmt(r) for r in reversed(runs))


def _format_week_ranges(weeks: list[tuple[int, int]]) -> str:
    if not weeks:
        return ""

    by_year: dict[int, list[int]] = {}
    for year, week in weeks:
        by_year.setdefault(year, []).append(week)

    parts: list[str] = []
    for year in sorted(by_year, reverse=True):
        values = sorted(set(by_year[year]))
        runs: list[tuple[int, int]] = []
        start = prev = values[0]
        for week in values[1:]:
            if week == prev + 1:
                prev = week
            else:
                runs.append((start, prev))
                start = prev = week
        runs.append((start, prev))

        for start, end in reversed(runs):
            if start == end:
                parts.append(f"{year}, Week {start}")
            else:
                parts.append(f"{year}, Weeks {start}--{end}")

    return ", ".join(parts)


def _teaching_when(entries: list[dict]) -> str:
    term_years = [
        (int(e["year"]), e["term"]) for e in entries if e.get("term") and e.get("year")
    ]
    weeks = [
        (int(e["year"]), int(e["week"]))
        for e in entries
        if e.get("week") and e.get("year")
    ]
    bare_years = [
        int(e["year"])
        for e in entries
        if e.get("year") and not e.get("term") and not e.get("week")
    ]

    if term_years:
        return _format_term_ranges(term_years)
    if weeks:
        return _format_week_ranges(weeks)
    if bare_years:
        ys = sorted(set(bare_years), reverse=True)
        return ", ".join(str(y) for y in ys)
    return ""


def _collect_teaching_roles(entries: list[dict]) -> list[str]:
    roles: list[str] = []
    for e in entries:
        role = str(e.get("role") or "").strip()
        if role and role not in roles:
            roles.append(role)
    return roles


def _merge_teaching_group(entries: list[dict]) -> dict:
    first = entries[0]
    merged = {
        "title": first["title"],
        "code": first.get("code"),
        "inst": first.get("inst"),
    }
    merged["when"] = _teaching_when(entries)
    merged["roles"] = _collect_teaching_roles(entries)

    seen: set[str] = set()
    coteachers: list = []
    for e in entries:
        for c in e.get("coteachers") or []:
            name = coauthor_name(c)
            if name and name not in seen:
                seen.add(name)
                coteachers.append(c)
    merged["coteachers"] = coteachers
    merged["_sort"] = min(_teaching_sort(e) for e in entries)
    return merged


def _merge_teaching_entries(entries: list[dict]) -> list[dict]:
    sub_groups: dict[tuple, list[dict]] = {}
    order_keys: list[tuple] = []
    for e in entries:
        key = (e.get("code") or None, e["title"])
        if key not in sub_groups:
            order_keys.append(key)
        sub_groups.setdefault(key, []).append(e)

    merged_entries = [_merge_teaching_group(sub_groups[k]) for k in order_keys]
    merged_entries.sort(key=lambda m: m["_sort"])
    return merged_entries


def _teaching_row_left(entry: dict) -> str:
    title = md(entry["title"])
    code = md(entry.get("code") or "")
    left = f"_{title}_"
    if code:
        left = f"{code}: {left}"
    if entry["coteachers"]:
        co = ", ".join(md(coauthor_name(c)) for c in entry["coteachers"])
        left += f", with {co}"
    return left


def teaching_section(entries: list[dict]) -> str:
    groups: dict[str, list[dict]] = {}
    for e in entries:
        groups.setdefault(e.get("inst", "(other)"), []).append(e)

    preferred = [
        "University of Pennsylvania",
        "State Correctional Institution Chester",
        "Canada/USA Mathcamp",
        "Reed College",
    ]
    ordered = [k for k in preferred if k in groups] + [
        k for k in groups if k not in preferred
    ]

    blocks: list[str] = []
    for inst in ordered:
        inst_entries = groups[inst]
        label = md(inst)
        inst_roles = _collect_teaching_roles(inst_entries)

        role_groups: dict[str, list[dict]] = {}
        for e in inst_entries:
            role = str(e.get("role") or "").strip()
            if role:
                role_groups.setdefault(role, []).append(e)

        lines = [
            "  [",
            f'    #text(weight: "bold")[{label}]',
            "    #v(0.1em)",
            "    #stack(spacing: 0.45em,",
        ]

        for role in inst_roles:
            role_entries = role_groups.get(role, [])
            if not role_entries:
                continue
            merged_entries = _merge_teaching_entries(role_entries)
            lines.append("      [")
            lines.append(f'        #text(style: "italic")[{md(role)}]')
            lines.append("        #v(0.1em)")
            lines.append("        #multi-line-list(list-args: (spacing: 0.5em),")
            for m in merged_entries:
                lines.append(
                    f"          cv-row2col([{_teaching_row_left(m)}], [{md(m['when'])}]),"
                )
            lines.append("        )")
            lines.append("      ],")

        lines.append("    )")
        lines.append("  ]")
        blocks.append("\n".join(lines))

    body = ",\n".join(blocks)
    return f"== Teaching Experience\n\n#list(spacing: 0.8em,\n{body},\n)\n\n"


def talks_section(research: list[dict], expository: list[dict]) -> str:
    combined = list(research) + list(expository)
    combined.sort(key=lambda t: date_key(t.get("date")), reverse=True)

    rows: list[tuple[str, str]] = []
    for t in combined:
        title = md(t["title"])
        venue = md(t.get("venue", ""))
        if t.get("venue_url"):
            venue = f'#link("{code_str(t["venue_url"])}")[{venue}]'
        date = md(month_year(t.get("date")))
        label = f"_{title}_"
        if venue:
            label += f", {venue}"
        rows.append((label, date))
    return _row_list("Talks", rows)


def service_section(entries: list[dict]) -> str:
    rows: list[tuple[str, str]] = []
    for s in entries:
        role = md(s["role"])
        venue = md(s["venue"])
        if s.get("url"):
            venue = f'#link("{code_str(s["url"])}")[{venue}]'
        date = md(s.get("date", ""))
        label = f"*{role}*, {venue}"
        if s.get("institution"):
            label += f", {md(s['institution'])}"
        if s.get("coorganizers"):
            co = ", ".join(md(coauthor_name(c)) for c in s["coorganizers"])
            label += f", with {co}"
        rows.append((label, date))
    return _row_list("Service and organization", rows)


# -------------------------------------------------------------------- build


def render() -> str:
    cv = load("cv")
    if not isinstance(cv, dict):
        raise RuntimeError("_data/cv.yaml must be a mapping")

    pieces = [PREAMBLE, header(cv), interests_section(cv)]

    if edu := load("education"):
        pieces.append(education_section(edu))
    if papers := load("papers"):
        pieces.append(papers_section(papers))
    if awards := load("awards"):
        pieces.append(awards_section(awards))
    if exp := load("research-experience"):
        pieces.append(experience_section(exp))
    if teaching := load("teaching"):
        pieces.append(teaching_section(teaching))

    research_talks = load("research-talks")
    expository_talks = load("expository-talks")
    if research_talks or expository_talks:
        pieces.append(talks_section(research_talks, expository_talks))

    if service := load("service"):
        pieces.append(service_section(service))

    return "".join(pieces)


def compile_pdf(typ_path: Path) -> None:
    typst = shutil.which("typst")
    if not typst:
        sys.exit("error: need `typst` on PATH to --compile")
    subprocess.run([typst, "compile", typ_path.name], cwd=typ_path.parent, check=True)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out",
        type=Path,
        default=ROOT / "assets" / "cv.typ",
        help="Path to write the .typ file (default: assets/cv.typ)",
    )
    ap.add_argument(
        "--compile",
        action="store_true",
        help="After writing .typ, compile to PDF with typst",
    )
    args = ap.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render())
    print(f"wrote {args.out.relative_to(ROOT)}")

    if args.compile:
        compile_pdf(args.out)
        print(f"wrote {args.out.with_suffix('.pdf').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
